version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/onlymacs-web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/apps/local-bridge"
    schedule:
      interval: "weekly"

  - package-ecosystem: "swift"
    directory: "/apps/onlymacs-macos"
    schedule:
      interval: "weekly"
